# 项目相关配置
springboot-init:
  # 名称
  name: springboot-init
  # 版本
  version: 1.0.0

# 开发环境配置
server:
  #服务器的HTTP端口
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.msb: debug
    org.springframework: warn

# Spring配置
spring:
  profiles:
    active: druid
  # redis 配置
#  redis:
#    # 地址
#    host: localhost
#    # 端口，默认为6379
#    port: 6379
#    # 密码
#    password:
#    # 连接超时时间
#    timeout: 10s
#    jedis:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 3
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
# MyBatis配置

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

## mybatis-plus配置
mybatis-plus:
  ## plus的实体别名包，不需要写出实体类的完整路径，只需要写出类名即可
  type-aliases-package: com.qf.**.domain
  ## mybatis  mapper.xml的位置
  mapper-locations: classpath:mapper/**/*Mapper.xml
  ## mybatis  config的配置文件位置

  config-location: classpath:mybatis/mybatis-config.xml
  ## 全局配置
  global-config:
    db-config:
      ## id生成策略为雪花id
      id-type: assign_id
    ## 不启用mybatis-plus的banner
    banner: false

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: qf123
  # 令牌有效期（默认30分钟）
  expireTime: 30